### ISSUE TITLE
"winston is not defined"

### ISSUE THREAD

**Issue by PatheticMustan** [btw6391/node-plugin-custom-registration-fields#1]
After lots of debugging, I found that this plugin can actually shut down the entire forum
Damn.
Ubuntu 16.04
MongoDB 4.0.6
Nodebb 1.12.1 (041cde4dbce64c8f748c81800fac8f6738bf0005)

```
2019-05-11T05:09:13.608Z [4567/11422] - info: Routes added
2019-05-11T05:09:13.615Z [4567/11422] - info: NodeBB Ready
2019-05-11T05:09:13.624Z [4567/11422] - info: Enabling 'trust proxy'
2019-05-11T05:09:13.631Z [4567/11422] - info: NodeBB is now listening on: 127.0.0.1:4567
2019-05-11T05:09:16.833Z [4567/11422] - warn: [deprecated] requiring core modules with `module.parent.require('./socket.io/admin/rooms')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
undefined
2019-05-11T05:11:53.823Z [4567/11422] - error: uncaughtException: winston is not defined
ReferenceError: winston is not defined
    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17
    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at /root/nodebb/src/user/data.js:114:4
    at /root/nodebb/src/user/data.js:120:4
    at /root/nodebb/node_modules/async/dist/async.js:473:16
    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at done (/root/nodebb/src/plugins/hooks.js:95:5) {"error":{},"stack":"ReferenceError: winston is not defined\n    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17\n    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)\n    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at /root/nodebb/src/user/data.js:114:4\n    at /root/nodebb/src/user/data.js:120:4\n    at /root/nodebb/node_modules/async/dist/async.js:473:16\n    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at done (/root/nodebb/src/plugins/hooks.js:95:5)","exception":true,"date":"Sat May 11 2019 05:11:53 GMT+0000 (Coordinated Universal Time)","process":{"pid":11422,"uid":0,"gid":0,"cwd":"/root/nodebb","execPath":"/usr/bin/node","version":"v10.15.3","argv":["/usr/bin/node","/root/nodebb/app.js"],"memoryUsage":{"rss":193978368,"heapTotal":155357184,"heapUsed":113030456,"external":39271596}},"os":{"loadavg":[0.01611328125,0.130859375,0.1455078125],"uptime":7860153},"trace":[{"column":17,"file":"/root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js","function":null,"line":102,"method":null,"native":false},{"column":14,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":114,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":120,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":5,"file":"/root/nodebb/src/plugins/hooks.js","function":"done","line":95,"method":null,"native":false}]}
2019-05-11T05:11:53.825Z [4567/11422] - error: winston is not defined
2019-05-11T05:11:53.825Z [4567/11422] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2019-05-11T05:11:53.827Z [4567/11422] - error: uncaughtException: winston is not defined
ReferenceError: winston is not defined
    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17
    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at /root/nodebb/src/user/data.js:114:4
    at /root/nodebb/src/user/data.js:120:4
    at /root/nodebb/node_modules/async/dist/async.js:473:16
    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at done (/root/nodebb/src/plugins/hooks.js:95:5) {"error":{},"stack":"ReferenceError: winston is not defined\n    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17\n    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)\n    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at /root/nodebb/src/user/data.js:114:4\n    at /root/nodebb/src/user/data.js:120:4\n    at /root/nodebb/node_modules/async/dist/async.js:473:16\n    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at done (/root/nodebb/src/plugins/hooks.js:95:5)","exception":true,"date":"Sat May 11 2019 05:11:53 GMT+0000 (Coordinated Universal Time)","process":{"pid":11422,"uid":0,"gid":0,"cwd":"/root/nodebb","execPath":"/usr/bin/node","version":"v10.15.3","argv":["/usr/bin/node","/root/nodebb/app.js"],"memoryUsage":{"rss":193978368,"heapTotal":155357184,"heapUsed":113142176,"external":39231652}},"os":{"loadavg":[0.01611328125,0.130859375,0.1455078125],"uptime":7860153},"trace":[{"column":17,"file":"/root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js","function":null,"line":102,"method":null,"native":false},{"column":14,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":114,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":120,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":5,"file":"/root/nodebb/src/plugins/hooks.js","function":"done","line":95,"method":null,"native":false}]}
2019-05-11T05:11:53.828Z [4567/11422] - error: winston is not defined
2019-05-11T05:11:53.828Z [4567/11422] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2019-05-11T05:11:53.829Z [4567/11422] - error: uncaughtException: winston is not defined
ReferenceError: winston is not defined
    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17
    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at /root/nodebb/src/user/data.js:114:4
    at /root/nodebb/src/user/data.js:120:4
    at /root/nodebb/node_modules/async/dist/async.js:473:16
    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at done (/root/nodebb/src/plugins/hooks.js:95:5) {"error":{},"stack":"ReferenceError: winston is not defined\n    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17\n    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)\n    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at /root/nodebb/src/user/data.js:114:4\n    at /root/nodebb/src/user/data.js:120:4\n    at /root/nodebb/node_modules/async/dist/async.js:473:16\n    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at done (/root/nodebb/src/plugins/hooks.js:95:5)","exception":true,"date":"Sat May 11 2019 05:11:53 GMT+0000 (Coordinated Universal Time)","process":{"pid":11422,"uid":0,"gid":0,"cwd":"/root/nodebb","execPath":"/usr/bin/node","version":"v10.15.3","argv":["/usr/bin/node","/root/nodebb/app.js"],"memoryUsage":{"rss":193978368,"heapTotal":155357184,"heapUsed":113212560,"external":38923572}},"os":{"loadavg":[0.01611328125,0.130859375,0.1455078125],"uptime":7860153},"trace":[{"column":17,"file":"/root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js","function":null,"line":102,"method":null,"native":false},{"column":14,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":114,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":120,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":5,"file":"/root/nodebb/src/plugins/hooks.js","function":"done","line":95,"method":null,"native":false}]}
2019-05-11T05:11:53.833Z [4567/11422] - error: winston is not defined
2019-05-11T05:11:53.833Z [4567/11422] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2019-05-11T05:11:53.834Z [4567/11422] - error: uncaughtException: winston is not defined
ReferenceError: winston is not defined
    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17
    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at /root/nodebb/src/user/data.js:114:4
    at /root/nodebb/src/user/data.js:120:4
    at /root/nodebb/node_modules/async/dist/async.js:473:16
    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at done (/root/nodebb/src/plugins/hooks.js:95:5) {"error":{},"stack":"ReferenceError: winston is not defined\n    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17\n    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)\n    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at /root/nodebb/src/user/data.js:114:4\n    at /root/nodebb/src/user/data.js:120:4\n    at /root/nodebb/node_modules/async/dist/async.js:473:16\n    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at done (/root/nodebb/src/plugins/hooks.js:95:5)","exception":true,"date":"Sat May 11 2019 05:11:53 GMT+0000 (Coordinated Universal Time)","process":{"pid":11422,"uid":0,"gid":0,"cwd":"/root/nodebb","execPath":"/usr/bin/node","version":"v10.15.3","argv":["/usr/bin/node","/root/nodebb/app.js"],"memoryUsage":{"rss":193978368,"heapTotal":155357184,"heapUsed":113275368,"external":38923572}},"os":{"loadavg":[0.01611328125,0.130859375,0.1455078125],"uptime":7860153},"trace":[{"column":17,"file":"/root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js","function":null,"line":102,"method":null,"native":false},{"column":14,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":114,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":120,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":5,"file":"/root/nodebb/src/plugins/hooks.js","function":"done","line":95,"method":null,"native":false}]}
2019-05-11T05:11:53.834Z [4567/11422] - error: winston is not defined
2019-05-11T05:11:53.834Z [4567/11422] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2019-05-11T05:11:53.834Z [4567/11422] - error: uncaughtException: winston is not defined
ReferenceError: winston is not defined
    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17
    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)
    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at /root/nodebb/src/user/data.js:114:4
    at /root/nodebb/src/user/data.js:120:4
    at /root/nodebb/node_modules/async/dist/async.js:473:16
    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)
    at /root/nodebb/node_modules/async/dist/async.js:969:16
    at done (/root/nodebb/src/plugins/hooks.js:95:5) {"error":{},"stack":"ReferenceError: winston is not defined\n    at /root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:102:17\n    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5324:14)\n    at next (/root/nodebb/node_modules/async/dist/async.js:5331:9)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at /root/nodebb/src/user/data.js:114:4\n    at /root/nodebb/src/user/data.js:120:4\n    at /root/nodebb/node_modules/async/dist/async.js:473:16\n    at next (/root/nodebb/node_modules/async/dist/async.js:5329:29)\n    at /root/nodebb/node_modules/async/dist/async.js:969:16\n    at done (/root/nodebb/src/plugins/hooks.js:95:5)","exception":true,"date":"Sat May 11 2019 05:11:53 GMT+0000 (Coordinated Universal Time)","process":{"pid":11422,"uid":0,"gid":0,"cwd":"/root/nodebb","execPath":"/usr/bin/node","version":"v10.15.3","argv":["/usr/bin/node","/root/nodebb/app.js"],"memoryUsage":{"rss":193978368,"heapTotal":155357184,"heapUsed":113336952,"external":38923572}},"os":{"loadavg":[0.01611328125,0.130859375,0.1455078125],"uptime":7860153},"trace":[{"column":17,"file":"/root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js","function":null,"line":102,"method":null,"native":false},{"column":14,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"nextTask","line":5324,"method":null,"native":false},{"column":9,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5331,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":114,"method":null,"native":false},{"column":4,"file":"/root/nodebb/src/user/data.js","function":null,"line":120,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/root/nodebb/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/root/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":5,"file":"/root/nodebb/src/plugins/hooks.js","function":"done","line":95,"method":null,"native":false}]}
2019-05-11T05:11:53.834Z [4567/11422] - error: winston is not defined
2019-05-11T05:11:53.834Z [4567/11422] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2019-05-11T05:11:53.835Z [4567/11422] - info: [app] Web server closed to connections.
2019-05-11T05:11:53.835Z [4567/11422] - error: Server is not running.
[cluster] Child Process (11422) has exited (code: 1, signal: null)
[cluster] Spinning up another process...
2019-05-11T05:11:54.125Z [4567/11482] - info: Initializing NodeBB v1.12.1 http://cpos.ml:4567
2019-05-11T05:11:55.325Z [4567/11482] - warn: [upgrade/appendPluginScripts] Unable to read plugin.json for plugin `nodebb-plugin-frontend-lodash`. Skipping.
2019-05-11T05:11:55.746Z [4567/11482] - info: [socket.io] Restricting access to origin: http://cpos.ml:*
2019-05-11T05:11:56.067Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./user')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:4:28)
2019-05-11T05:11:56.068Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./database')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:5:26)
2019-05-11T05:11:56.068Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./notifications')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:6:37)
2019-05-11T05:11:56.069Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./routes/helpers')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:7:36)
2019-05-11T05:11:56.069Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./controllers/helpers')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-checkin/library.js:8:41)
2019-05-11T05:11:56.204Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./user')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /root/nodebb/node_modules/nodebb-plugin-discord-notification/library.js:4:27
2019-05-11T05:11:56.213Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./topics')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /root/nodebb/node_modules/nodebb-plugin-discord-notification/library.js:5:29
2019-05-11T05:11:56.221Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./categories')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /root/nodebb/node_modules/nodebb-plugin-discord-notification/library.js:6:33
2019-05-11T05:11:56.222Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('../public/src/modules/translator')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /root/nodebb/node_modules/nodebb-plugin-discord-notification/library.js:7:33
2019-05-11T05:11:56.223Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./meta')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /root/nodebb/node_modules/nodebb-plugin-discord-notification/library.js:8:27
2019-05-11T05:11:56.344Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./database')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
undefined
2019-05-11T05:11:56.344Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./user')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
undefined
2019-05-11T05:11:56.345Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./utils')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
undefined
2019-05-11T05:11:56.345Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./socket.io/plugins')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
undefined
2019-05-11T05:11:56.348Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./user')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /root/nodebb/node_modules/nodebb-plugin-secret-login/index.js:5:26
2019-05-11T05:11:56.350Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./user')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:12:26)
2019-05-11T05:11:56.350Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./meta')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:13:26)
2019-05-11T05:11:56.351Z [4567/11482] - warn: [deprecated] requiring core modules with `module.parent.require('./database')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at Object.<anonymous> (/root/nodebb/node_modules/nodebb-plugin-registration-field-custom/library.js:14:24)
```

**Comment by PatheticMustan** [comment]
🤔 uh, is Front End Lodash required...
